# Generated by Django 4.1 on 2024-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slideritem_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ['my_order'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
